name       : solus-hardware-config
version    : 1
release    : 1
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v1/solus-hardware-config-1.tar.xz : a764af4a5f3117fe6341f553b537e89fdf9aac728989c3aaaba52bf10724e0e8
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
