name       : solus-hardware-config
version    : 4
release    : 4
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v4/solus-hardware-config-4.tar.xz : 15dc703eb156b93c7f9040178694f04614fc082aff2dfa2b79ff860d2d5f63ea
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
