name       : solus-hardware-config
version    : '16'
release    : 25
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v16/solus-hardware-config-16.tar.xz : 5ffae46fa5b54cbf925dd9fdeeabfeea272b9280fd9a8efa32376d6688110690
license    : MIT
summary    : Solus Hardware configuration support
component  : desktop.core
description: |
    Solus Hardware configuration support
rundeps    :
    - xorg-driver-video-intel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    # Pre-activate it
    ln -sv ../cpu-powersave.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
