name       : solus-hardware-config
version    : 2
release    : 2
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v2/solus-hardware-config-2.tar.xz : d098c9ee07bc99617a9ba1d6cf388ee86eef4813b855cb1d7fe2f01d0e65bae2
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
