name       : solus-hardware-config
version    : '16'
release    : 29
source     :
    - git|https://github.com/getsolus/solus-hardware-config.git : bea6b92680b40c1fee2aa633daa04989857d70d5
license    : MIT
summary    : Solus Hardware configuration support
component  : desktop.core
description: |
    Solus Hardware configuration support
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    # Pre-activate it
    ln -sv ../cpu-powersave.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
