name       : solus-hardware-config
version    : '12'
release    : 16
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v12/solus-hardware-config-12.tar.xz : dd04630cdb57ad890fb8a9e46ded30f36e7e92263999a971942a75c50bc1d1e0
license    : MIT
summary    : Solus Hardware configuration files
component  : desktop.core
description: |
    Solus Hardware configuration files
rundeps    :
    - linux-tools-cpupower
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    # Pre-activate it
    ln -sv ../on-demand-cpupower.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
