name       : solus-hardware-config
version    : 8
release    : 11
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v8/solus-hardware-config-8.tar.xz : db7612b1168d07b558e0f219b17ae9e57ce712b7fb915a207c23debce10c933e
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
rundeps    :
    - thermald
    - xorg-driver-input-libinput
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
