name       : solus-hardware-config
version    : '14'
release    : 19
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v14/solus-hardware-config-14.tar.xz : 7c81bc8459758a8ee2d7c1485ebad706c2453e45c28992a378f64d3be413b4fc
license    : MIT
summary    : Solus Hardware configuration files
component  : desktop.core
description: |
    Solus Hardware configuration files
rundeps    :
    - linux-tools-cpupower
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-Intel-Wireless-N-as-it-is-miserably-broken.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    # Pre-activate it
    ln -sv ../on-demand-cpupower.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
