name       : solus-hardware-config
version    : '13'
release    : 17
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v13/solus-hardware-config-13.tar.xz : 16e0001269a8e4166d3463d974065d44957318de055cfe41c0f7e0b1e471d3a8
license    : MIT
summary    : Solus Hardware configuration files
component  : desktop.core
description: |
    Solus Hardware configuration files
rundeps    :
    - linux-tools-cpupower
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    # Pre-activate it
    ln -sv ../on-demand-cpupower.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
