name       : solus-hardware-config
version    : 6
release    : 8
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v6/solus-hardware-config-6.tar.xz : 9245b221f9239bddddf8981d591232ba43df219620b353d3560e73c93f86560a
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
rundeps    :
    - tlp
    - thermald
    - xorg-driver-input-libinput
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
