name       : solus-hardware-config
version    : 3
release    : 3
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v3/solus-hardware-config-3.tar.xz : 86047c8f0d282a3867933c15b3fec3203d81183e07aaad299821da07bc9d1fd2
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
