name       : solus-hardware-config
version    : 9
release    : 13
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v9/solus-hardware-config-9.tar.xz : aada492822ceb935012c97fa04e2623f75fd2e2daabf0cc80e4844bebe553478
license    : MIT
summary    : Solus Hardware configuration files
component  : desktop.core
description: |
    Solus Hardware configuration files
rundeps    :
    - thermald
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
