name       : solus-hardware-config
version    : '16'
release    : 30
source     :
    - git|https://github.com/getsolus/solus-hardware-config.git : 83f675849f76216f26efd5686a142570d45035c1
license    : MIT
summary    : Solus Hardware configuration support
component  : desktop.core
description: |
    Solus Hardware configuration support
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    # Pre-activate it
    ln -sv ../cpu-powersave.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
