name       : solus-hardware-config
version    : 7
release    : 10
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v7/solus-hardware-config-7.tar.xz : 2365cd2f485783fdb97d3b744ad0a75cfd2f5f9cc2c52a1f34e6806ad5a299e2
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
rundeps    :
    - thermald
    - xorg-driver-input-libinput
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
