name       : solus-hardware-config
version    : 5
release    : 5
source     :
    - https://github.com/solus-project/solus-hardware-config/releases/download/v5/solus-hardware-config-5.tar.xz : c1e98f62307e8cb84a03903268f54953c5160a59b4989c83f8d6effe3d0b03fe
license    : MIT
summary    : Solus Hardware configuration files
description: |
    Solus Hardware configuration files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
